export const KEY_TERMS_DATA = [
  {
    id: 'ehr',
    acronym: 'EHR',
    title: 'Electronic Health Record',
    titleBn: 'ইলেক্ট্রনিক হেলথ রেকর্ড',
    category: 'Core Systems',
    categoryBn: 'মূল স্বাস্থ্য ব্যবস্থা',
    badgeColor: 'emerald',
    simpleExplanationEn: 'The core software system hospitals use to store patient charts, diagnoses, and orders (like Epic, Cerner, or an open-source clone).',
    simpleExplanationBn: 'হাসপাতালের প্রধান কেন্দ্রীয় সফটওয়্যার যেখানে রোগীর বিস্তারিত চার্ট, রোগ নির্ণয়ের ইতিহাস, চিকিৎসকের প্রেসক্রিপশন ও অপারেশনের অর্ডার সংরক্ষিত থাকে (যেমন Epic, Cerner বা ওপেন সোর্স সমকক্ষ সিস্টেম)।',
    otImpactEn: 'Provides patient context, operative bookings, and clinical history directly to the OT safety gate screen.',
    otImpactBn: 'অস্ত্রোপচার শুরুর আগে রোগীর সঠিক পরিচয়, অপারেশনের বুকিং এবং পূর্ববর্তী চিকিৎসার ইতিহাস সরাসরি ওটি স্ক্রিনে সরবরাহ করে।'
  },
  {
    id: 'fhir',
    acronym: 'FHIR',
    title: 'Fast Healthcare Interoperability Resources',
    titleBn: 'ফাস্ট হেলথকেয়ার ইন্টারঅপারেবিলিটি রিসোর্সেস',
    category: 'APIs & Data Standards',
    categoryBn: 'এপিআই ও ডেটা স্ট্যান্ডার্ড',
    badgeColor: 'teal',
    simpleExplanationEn: 'A modern set of rules and JSON formats that allows software to read and write hospital records using standard web APIs (HTTP GET/POST), just like Twitter or Stripe APIs.',
    simpleExplanationBn: 'আধুনিক ওয়েব স্ট্যান্ডার্ড ও JSON ফরম্যাটের একটি আন্তর্জাতিক মানদণ্ড, যা ওয়েব এপিআই (HTTP GET/POST) ব্যবহার করে যেকোনো সফটওয়্যারকে হাসপাতালের ডেটা পড়তে ও লিখতে দেয় — ঠিক যেমন Twitter বা Stripe এর এপিআই কাজ করে।',
    otImpactEn: 'Powers our RESTful queries for Patient, Procedure, AllergyIntolerance, DocumentReference, and Observation resources.',
    otImpactBn: 'আমাদের ওটি প্ল্যাটফর্ম সরাসরি FHIR REST API দিয়ে রোগীর সার্জিক্যাল অর্ডার, সম্মতিপত্র, অ্যান্টিবায়োটিক অ্যালার্জি ও ল্যাব টেস্টের তথ্য স্বয়ংক্রিয়ভাবে ফেচ করে।'
  },
  {
    id: 'hl7v2',
    acronym: 'HL7 v2',
    title: 'Health Level Seven Version 2',
    titleBn: 'হেলথ লেভেল সেভেন ভার্সন ২',
    category: 'Legacy Hospital Messaging',
    categoryBn: 'ঐতিহ্যবাহী হাসপাতাল মেসেজিং',
    badgeColor: 'blue',
    simpleExplanationEn: 'An older, 1980s text-message format (separated by pipe | characters) still used inside almost every hospital for real-time notifications, like when a patient checks into a room or pharmacy orders are sent.',
    simpleExplanationBn: '১৯৮০-এর দশকের একটি পাইপ (|) বিভক্ত বার্তা ফরম্যাট, যা এখনও বিশ্বের অধিকাংশ হাসপাতালে তাৎক্ষণিক বিজ্ঞপ্তির জন্য ব্যবহৃত হয় — যেমন রোগী যখন ওটি রুমে প্রবেশ করেন বা ফার্মেসিতে জরুরি ওষুধের রিকোয়েস্ট যায়।',
    otImpactEn: 'Feeds real-time ADT (Admission, Discharge, Transfer) events to signal when the surgical patient arrives on the operating table.',
    otImpactBn: 'হাসপাতালের কেন্দ্রীয় ভর্তি ও মনিটর ব্যবস্থা থেকে রোগী ওটি টেবিলে পৌঁছানোর রিয়েল-টাইম নোটিফিকেশন পাঠায়।'
  },
  {
    id: 'smart-on-fhir',
    acronym: 'SMART on FHIR',
    title: 'Substitutable Medical Applications, Reusable Technologies',
    titleBn: 'স্মার্ট অন ফায়ার (নিরাপদ অ্যাপ লঞ্চ ফ্রেমওয়ার্ক)',
    category: 'Authentication & Security',
    categoryBn: 'নিরাপত্তা ও অথেন্টিকেশন',
    badgeColor: 'indigo',
    simpleExplanationEn: 'A secure login workflow (OAuth 2.0) that lets a custom web app launch directly inside a doctor’s EHR screen without having to log in separately.',
    simpleExplanationBn: 'OAuth 2.0 ও PKCE ভিত্তিক একটি নিরাপদ ও প্রমিত লগইন ওয়ার্কফ্লো, যা একজন চিকিৎসক বা সার্জনকে আলাদা ইউজারনেম/পাসওয়ার্ড ছাড়াই সরাসরি তার EHR মনিটরের ভেতরেই এই অ্যাপটি এক ক্লিকে চালু করতে দেয়।',
    otImpactEn: 'Guarantees the surgical app opens strictly bound to the authenticated surgeon and the selected operating theater patient.',
    otImpactBn: 'নিশ্চিত করে যে অ্যাপটি শুধুমাত্র লগইনকৃত সার্জন এবং ওটি টেবিলে থাকা নির্দিষ্ট রোগীর প্রেক্ষাপটেই কঠোরভাবে পরিচালিত হচ্ছে।'
  },
  {
    id: 'rxnorm',
    acronym: 'RxNorm',
    title: 'Standardized Medication Terminology',
    titleBn: 'প্রেসক্রিপশন ও ঔষধের প্রমিত পরিভাষা',
    category: 'Clinical Terminology',
    categoryBn: 'ক্লিনিক্যাল পরিভাষা',
    badgeColor: 'purple',
    simpleExplanationEn: 'A standardized catalog of medication names, strengths, and ingredients run by the US National Library of Medicine (NLM) so computers never confuse brand names with generic chemical formulas.',
    simpleExplanationBn: 'আমেরিকান ন্যাশনাল লাইব্রেরি অব মেডিসিন (NLM) পরিচালিত ওষুধের নাম, ক্ষমতা ও উপাদানের সর্বজনীন ক্যাটালগ — যাতে কম্পিউটার বিভিন্ন ব্র্যান্ডের বাণিজ্যিক নামের সাথে জেনেরিক মূল উপাদানের কোনো বিভ্রান্তি না করে।',
    otImpactEn: 'Cross-checks planned pre-incision prophylactic antibiotics against the patient\'s documented drug allergies.',
    otImpactBn: 'অপারেশনের শুরুতে যে অ্যান্টিবায়োটিক দেওয়ার পরিকল্পনা করা হয়েছে, রোগীর সেই নির্দিষ্ট জেনেরিক উপাদানে অ্যালার্জি আছে কি না তা নিখুঁতভাবে যাচাই করে।'
  },
  {
    id: 'loinc',
    acronym: 'LOINC',
    title: 'Logical Observation Identifiers Names and Codes',
    titleBn: 'ল্যাবরেটরি ও ক্লিনিক্যাল পর্যবেক্ষণের সর্বজনীন কোড',
    category: 'Clinical Terminology',
    categoryBn: 'ক্লিনিক্যাল পরিভাষা',
    badgeColor: 'amber',
    simpleExplanationEn: 'A universal database of ID numbers for laboratory tests and vital signs (e.g., one specific code always means "Systolic Blood Pressure," regardless of which hospital took the reading).',
    simpleExplanationBn: 'ল্যাবরেটরি টেস্ট এবং শারীরিক লক্ষণের জন্য একটি আন্তর্জাতিক সর্বজনীন আইডি নম্বর ডেটাবেস — যেমন একটি নির্দিষ্ট কোড সর্বদা "Systolic Blood Pressure" বা "Platelet Count" বোঝাবে, তা যেকোনো হাসপাতালেই টেস্ট করা হোক না কেন।',
    otImpactEn: 'Identifies critical coagulation biomarkers (INR: 34714-6, PT: 5902-2, aPTT: 3173-2, Platelets: 777-3) to prevent intraoperative bleeding.',
    otImpactBn: 'অস্ত্রোপচারের সময় অতিরিক্ত রক্তক্ষরণ ঠেকাতে রোগীর রক্ত জমাট বাঁধার ক্ষমতা (INR, PT, aPTT) ও প্লেটলেটের মাত্রা আন্তর্জাতিক কোডে যাচাই করে।'
  },
  {
    id: 'snomed-cpt',
    acronym: 'SNOMED-CT & CPT',
    title: 'Clinical Diseases & Surgical Procedure Code Lists',
    titleBn: 'রোগের আন্তর্জাতিক পরিভাষা ও সার্জিক্যাল প্রক্রিয়া কোড',
    category: 'Clinical Terminology',
    categoryBn: 'ক্লিনিক্যাল পরিভাষা',
    badgeColor: 'rose',
    simpleExplanationEn: 'Standard code lists used for clinical conditions/diseases (SNOMED) and billable medical/surgical procedures (CPT).',
    simpleExplanationBn: 'রোগ ও শারীরিক জটিলতার সুনির্দিষ্ট ক্লিনিক্যাল তালিকা (SNOMED-CT) এবং সম্পাদনযোগ্য বা বিলযোগ্য অস্ত্রোপচারের প্রমিত কোড তালিকা (CPT)।',
    otImpactEn: 'Validates that the booked CPT procedure (e.g., 47562 Laparoscopic Cholecystectomy) matches the patient\'s documented SNOMED diagnosis (e.g., 28273000 Gallstone disease), eliminating wrong-procedure risks.',
    otImpactBn: 'নির্ধারিত সার্জারি কোডের সাথে রোগীর ডকুমেন্টেড রোগ নির্ণয়ের কোড মিলিয়ে ভুল অপারেশনের মারাত্মক ঝুঁকি সম্পূর্ণরূপে দূর করে।'
  },
  {
    id: 'hipaa-phi',
    acronym: 'HIPAA & PHI',
    title: 'Health Insurance Portability & Accountability Act / Protected Health Information',
    titleBn: 'স্বাস্থ্য তথ্য সুরক্ষা আইন এবং সংরক্ষিত স্বাস্থ্য তথ্য',
    category: 'Privacy & Legal',
    categoryBn: 'গোপনীয়তা ও আইন',
    badgeColor: 'red',
    simpleExplanationEn: 'Protected Health Information (PHI) is any private data that can identify a patient (name, birth date, phone number). HIPAA is the US law that imposes heavy fines if software leaks PHI or stores it insecurely.',
    simpleExplanationBn: 'সুরক্ষিত স্বাস্থ্য তথ্য (PHI) হলো রোগীর যেকোনো ব্যক্তিগত তথ্য যা দ্বারা তাকে শনাক্ত করা যায় (নাম, জন্মতারিখ, এনআইডি, ফোন)। HIPAA হলো আইন যা রোগীর তথ্য কোনো সফটওয়্যার অনিরাপদভাবে সংরক্ষণ বা ফাঁস করলে কঠোর শাস্তি ও জরিমানা ধার্য করে।',
    otImpactEn: 'All clinical evidence, identifiers, and audit trails in ORBIT are encrypted at rest, masked in logs, and stored in compliance with privacy mandates.',
    otImpactBn: 'আমাদের ওটি প্ল্যাটফর্মে রোগীর সমস্ত তথ্য, স্বাক্ষর এবং চেকলিস্টের ইতিহাস কঠোরভাবে এনক্রিপ্ট করে সংরক্ষণ করা হয়।'
  },
  {
    id: 'baa',
    acronym: 'BAA',
    title: 'Business Associate Agreement',
    titleBn: 'বিজনেস অ্যাসোসিয়েট চুক্তি',
    category: 'Privacy & Legal',
    categoryBn: 'গোপনীয়তা ও আইন',
    badgeColor: 'sky',
    simpleExplanationEn: 'A legally binding contract required under HIPAA when an outside developer or software company handles hospital patient data.',
    simpleExplanationBn: 'HIPAA আইনের অধীনে একটি বাধ্যতামূলক আইনি চুক্তি, যা যেকোনো সফটওয়্যার কোম্পানি বা ডেভেলপারকে হাসপাতালের সাথে করতে হয় যখন তারা রোগীর স্পর্শকাতর স্বাস্থ্য তথ্য পরিচালনা বা প্রক্রিয়াজাত করে।',
    otImpactEn: 'Defines the legal boundaries and security liabilities under which this OT safety software integrates with hospital infrastructure.',
    otImpactBn: 'হাসপাতালের আইটি সিস্টেমের সাথে এই ওটি সফটওয়্যার সংযুক্ত করার ক্ষেত্রে ডেটা নিরাপত্তার আইনি দায়িত্ব ও জবাবদিহিতা নির্ধারণ করে।'
  },
  {
    id: 'uscdi',
    acronym: 'USCDI',
    title: 'United States Core Data for Interoperability',
    titleBn: 'ইন্টারঅপারেবিলিটির জন্য প্রমিত জাতীয় স্বাস্থ্য ডেটা ফ্রেমওয়ার্ক',
    category: 'National Standards',
    categoryBn: 'জাতীয় মানদণ্ড',
    badgeColor: 'violet',
    simpleExplanationEn: 'A federally mandated checklist of minimum health data classes (allergies, vital signs, notes) that every health app must support sharing.',
    simpleExplanationBn: 'স্বাস্থ্য তথ্য আদান-প্রদানের জন্য একটি সরকার-অনুমোদিত বাধ্যতামূলক ন্যূনতম চেকলিস্ট (যেমন অ্যালার্জি, গুরুত্বপূর্ণ লক্ষণ, ক্লিনিক্যাল নোট ইত্যাদি) যা প্রতিটি স্বাস্থ্য সফটওয়্যারকে শেয়ার করার সক্ষমতা রাখতে হয়।',
    otImpactEn: 'Ensures the pre-surgical safety gate can query a predictable, guaranteed set of clinical data from any certified hospital EHR.',
    otImpactBn: 'নিশ্চিত করে যে যেকোনো সার্টিফাইড হাসপাতালের EHR থেকে আমাদের সেফটি গেট নির্দিষ্ট ও মানসম্মত ক্লিনিক্যাল ডেটা নির্বিঘ্নে ফেচ করতে পারবে।'
  },
  {
    id: 'hie-tefca',
    acronym: 'HIE & TEFCA',
    title: 'Health Information Exchange & Trusted Exchange Framework',
    titleBn: 'স্বাস্থ্য তথ্য বিনিময় নেটওয়ার্ক এবং জাতীয় বিশ্বস্ত ফ্রেমওয়ার্ক',
    category: 'Interoperability Networks',
    categoryBn: 'তথ্য বিনিময় নেটওয়ার্ক',
    badgeColor: 'emerald',
    simpleExplanationEn: 'An HIE (Health Information Exchange) is a network allowing different regional hospitals to share records. TEFCA is a nationwide government agreement connecting all these regional networks together into one trusted pipeline.',
    simpleExplanationBn: 'HIE হলো একটি আঞ্চলিক নেটওয়ার্ক যার মাধ্যমে বিভিন্ন হাসপাতাল নিজেদের মধ্যে রোগীর পূর্ববর্তী চিকিৎসা রেকর্ড শেয়ার করতে পারে। আর TEFCA হলো জাতীয় সরকারি চুক্তি যা দেশের সমস্ত আঞ্চলিক নেটওয়ার্ককে একটি একক সুরক্ষিত পাইপলাইনে যুক্ত করে।',
    otImpactEn: 'Enables our surgical safety gate to fetch cross-institutional surgical history, implants, and blood type records even if performed at other hospitals.',
    otImpactBn: 'রোগীর অন্য কোনো হাসপাতালে অতীতে সার্জারি, ইমপ্লান্ট বা অ্যালার্জির ইতিহাস থাকলে তা জাতীয় নেটওয়ার্কের মাধ্যমে ওটি টিমের কাছে তাৎক্ষণিক দৃশ্যমান করে তোলে।'
  }
];
