import { POLICY, SYSTEM } from '../../config/clinicalPolicy.js';
export const SCENARIOS = [
  { id: 'complete', name: 'Complete evidence', description: 'All example checks pass; team review is still required.' },
  { id: 'allergy', name: 'Antibiotic allergy', description: 'The planned cefazolin conflicts with an active allergy.' },
  { id: 'consent', name: 'Consent mismatch', description: 'Signed consent references a different surgery order.' },
  { id: 'stale', name: 'Outdated labs', description: 'The INR result is older than the example policy allows.' },
  { id: 'abnormal', name: 'Abnormal platelets', description: 'The platelet count is outside the example range.' }
];
const coded = (system, code, display) => ({ coding: [{ system, code, display }], text: display });
export function demoData(scenario = 'complete', epoch = new Date().toISOString()) {
  const now = new Date(epoch).getTime();
  const iso = h => new Date(now + h * 3600000).toISOString();
  const patient = { resourceType: 'Patient', id: 'demo-patient', identifier: [{ system: 'urn:orbit:synthetic-mrn', value: 'DEMO-2048' }], name: [{ given: ['Alex'], family: 'Morgan' }], gender: 'female', birthDate: '1990-04-18' };
  const subject = { reference: `Patient/${patient.id}` };
  const encounter = { resourceType: 'Encounter', id: 'demo-encounter', status: 'in-progress', class: { system: 'http://terminology.hl7.org/CodeSystem/v3-ActCode', code: 'IMP' }, subject, period: { start: iso(-8) }, location: [{ location: { display: 'Operating room 03' } }] };
  const surgery = { resourceType: 'ServiceRequest', id: 'demo-surgery', status: 'active', intent: 'order', category: [coded(SYSTEM.snomed, '387713003', 'Surgical procedure')], code: coded(SYSTEM.cpt, '44970', 'Laparoscopic appendectomy'), subject, encounter: { reference: 'Encounter/demo-encounter' }, occurrenceDateTime: iso(2), authoredOn: iso(-8), reasonReference: [{ reference: 'Condition/demo-diagnosis' }], bodySite: [coded(SYSTEM.snomed, '66754008', 'Appendix structure')] };
  const condition = { resourceType: 'Condition', id: 'demo-diagnosis', clinicalStatus: coded('http://terminology.hl7.org/CodeSystem/condition-clinical', 'active', 'Active'), verificationStatus: coded('http://terminology.hl7.org/CodeSystem/condition-ver-status', 'confirmed', 'Confirmed'), code: coded(SYSTEM.snomed, '74400008', 'Appendicitis'), subject, encounter: { reference: 'Encounter/demo-encounter' } };
  const surgeryRef = scenario === 'consent' ? 'ServiceRequest/different-surgery' : 'ServiceRequest/demo-surgery';
  const document = { resourceType: 'DocumentReference', id: 'demo-consent-form', status: 'current', docStatus: 'final', type: { text: 'Synthetic signed treatment consent' }, subject, date: iso(-4), context: { related: [{ reference: surgeryRef }] }, content: [{ attachment: { contentType: 'text/plain', title: 'Synthetic consent — not a real signature', data: Buffer.from('SYNTHETIC DEMO ONLY. Alex Morgan consented to the example appendectomy order. This is not a legal consent document.').toString('base64') } }] };
  const consent = { resourceType: 'Consent', id: 'demo-consent', status: 'active', scope: coded('http://terminology.hl7.org/CodeSystem/consentscope', 'treatment', 'Treatment'), category: [{ text: 'Procedure-specific informed consent' }], patient: subject, dateTime: iso(-4), sourceReference: { reference: 'DocumentReference/demo-consent-form' }, verification: [{ verified: true, verifiedWith: subject, verificationDate: iso(-4) }], provision: { type: 'permit', period: { start: iso(-5), end: iso(24) }, code: [surgery.code], data: [{ meaning: 'instance', reference: { reference: surgeryRef } }] } };
  const provenance = { resourceType: 'Provenance', id: 'demo-signature', target: [{ reference: 'Consent/demo-consent' }, { reference: 'DocumentReference/demo-consent-form' }], recorded: iso(-4), agent: [{ who: subject }], signature: [{ type: [{ system: 'urn:iso-astm:E1762-95:2013', code: '1.2.840.10065.1.12.1.1', display: "Author's Signature" }], when: iso(-4), who: subject, sigFormat: 'text/plain', data: Buffer.from('SYNTHETIC signature evidence; no cryptographic assurance').toString('base64') }] };
  const observations = POLICY.labs.map((rule, i) => ({ resourceType: 'Observation', id: `demo-${rule.id}`, status: 'final', category: [coded('http://terminology.hl7.org/CodeSystem/observation-category', 'laboratory', 'Laboratory')], code: coded(SYSTEM.loinc, rule.codes[0], rule.label), subject, encounter: { reference: 'Encounter/demo-encounter' }, effectiveDateTime: iso(scenario === 'stale' && rule.id === 'inr' ? -72 : -3), issued: iso(-2.8), valueQuantity: { value: scenario === 'abnormal' && i === 0 ? 48 : [242, 1.0, 12.4, 29][i], unit: rule.unit, system: SYSTEM.ucum, code: rule.unit }, referenceRange: [{ low: { value: rule.min, unit: rule.unit }, high: { value: rule.max, unit: rule.unit }, text: 'Synthetic example range; not a clinical recommendation' }] }));
  const allergy = { resourceType: 'AllergyIntolerance', id: 'demo-allergy', clinicalStatus: coded('http://terminology.hl7.org/CodeSystem/allergyintolerance-clinical', 'active', 'Active'), verificationStatus: coded('http://terminology.hl7.org/CodeSystem/allergyintolerance-verification', 'confirmed', 'Confirmed'), code: scenario === 'allergy' ? coded(SYSTEM.rxnorm, '2180', 'Cefazolin') : coded(SYSTEM.snomed, POLICY.noKnownAllergyCode, 'No known allergy'), patient: subject, recordedDate: iso(-1), lastOccurrence: scenario === 'allergy' ? iso(-200) : undefined, ...(scenario === 'allergy' ? { criticality: 'high', reaction: [{ manifestation: [coded(SYSTEM.snomed, '39579001', 'Anaphylaxis')], severity: 'severe' }] } : {}) };
  const medication = { resourceType: 'MedicationRequest', id: 'demo-antibiotic', status: 'active', intent: 'order', medicationCodeableConcept: coded(SYSTEM.rxnorm, '2180', 'Cefazolin'), subject, encounter: { reference: 'Encounter/demo-encounter' }, basedOn: [{ reference: 'ServiceRequest/demo-surgery' }], authoredOn: iso(-2), dosageInstruction: [{ text: 'Synthetic planned peri-operative prophylaxis; verify dose and timing in the EHR.' }] };
  return { patient, encounter, procedures: [surgery], conditions: [condition], consents: [consent], documents: [document], provenance: [provenance], observations, allergies: [allergy], medications: [medication], issues: [], mode: 'demo', fetchedAt: new Date().toISOString() };
}
