import test from 'node:test';
import assert from 'node:assert/strict';
import { demoData } from '../src/services/clinical/demoPatientService.js';
import { evaluate, caseFingerprint, patientMatches } from '../src/services/clinical/safetyEvaluationService.js';
import { SYSTEM } from '../src/config/clinicalPolicy.js';
const epoch = '2026-09-21T08:00:00.000Z', now = Date.parse(epoch);
const dataset = () => demoData('complete', epoch);
const run = data => evaluate(data, 'demo-surgery', { now });
const c = (data, id) => run(data).checks.find(c => c.id === id);
test('complete synthetic evidence requires team review, never automatic surgical clearance', () => {
  const result = run(dataset()); assert.equal(result.status, 'reviewable'); assert.equal(result.passed, 4);
});
test('live evidence is blocked until a local clinical policy is configured', () => {
  const d = dataset(); d.mode = 'ehr'; assert.equal(run(d).status, 'blocked');
});
for (const scenario of ['allergy', 'consent', 'abnormal']) test(`${scenario} scenario blocks reviewed records`, () => assert.equal(run(demoData(scenario, epoch)).status, 'blocked'));
test('stale INR never passes', () => { const a = run(demoData('stale', epoch)); assert.equal(a.status, 'review'); assert.equal(a.labs[1].status, 'review'); });
test('missing allergy list is unknown, not negative', () => { const d = dataset(); d.allergies = []; assert.equal(c(d, 'allergy').status, 'review'); });
test('no-known-allergy cannot mask a positive allergy', () => { const d = dataset(); d.allergies.push(demoData('allergy', epoch).allergies[0]); assert.equal(c(d, 'allergy').status, 'block'); });
test('class-level allergy is escalated, not a blanket drug contraindication', () => { const d = demoData('allergy', epoch); d.allergies[0].code = { coding: [{ system: SYSTEM.snomed, code: '373270004' }] }; assert.equal(c(d, 'allergy').status, 'review'); });
test('unmapped allergy is unresolved', () => { const d = demoData('allergy', epoch); d.allergies[0].code = { text: 'Unmapped medication allergy' }; assert.equal(c(d, 'allergy').status, 'review'); });
test('historical allergy cannot be silently discarded', () => { const d = demoData('allergy', epoch); d.allergies[0].clinicalStatus.coding[0].code = 'resolved'; assert.equal(c(d, 'allergy').status, 'review'); });
test('prophylaxis must be linked to the selected surgery', () => { const d = dataset(); d.medications[0].basedOn = []; assert.equal(c(d, 'allergy').status, 'review'); });
test('unmapped medication cannot pass the dictionary check', () => { const d = dataset(); d.medications[0].medicationCodeableConcept.coding[0].code = 'unmapped'; assert.equal(c(d, 'allergy').status, 'review'); });
test('consent must be treatment consent, not privacy consent', () => { const d = dataset(); d.consents[0].scope.coding[0].code = 'patient-privacy'; assert.equal(c(d, 'consent').status, 'block'); });
test('consent must remain valid through the scheduled surgery', () => { const d = dataset(); d.consents[0].provision.period.end = epoch; assert.equal(c(d, 'consent').status, 'block'); });
test('consent requires a finalized current source document', () => { const d = dataset(); d.documents[0].docStatus = 'preliminary'; assert.equal(c(d, 'consent').status, 'block'); });
test('consent status alone does not prove a signed document', () => { const d = dataset(); d.provenance = []; assert.equal(c(d, 'consent').status, 'block'); });
test('signature evidence must identify the launched patient', () => { const d = dataset(); d.provenance[0].signature[0].who.reference = 'Patient/different'; assert.equal(c(d, 'consent').status, 'block'); });
test('nested consent rules cannot be flattened into approval', () => { const d = dataset(); d.consents[0].provision.provision = [{ type: 'deny' }]; assert.equal(c(d, 'consent').status, 'block'); });
test('withdrawn related consent cannot be bypassed by an active consent', () => { const d = dataset(); d.consents.push({ ...structuredClone(d.consents[0]), id: 'withdrawn', status: 'inactive' }); assert.equal(c(d, 'consent').status, 'block'); });
test('same CPT code for a different order is not enough', () => assert.equal(c(demoData('consent', epoch), 'consent').status, 'block'));
test('CPT mapping is system-qualified', () => { const d = dataset(); d.procedures[0].code.coding[0].system = 'urn:lookalike'; assert.equal(c(d, 'procedure').status, 'review'); });
test('an unrelated matching diagnosis cannot satisfy an order', () => { const d = dataset(); d.procedures[0].reasonReference = []; assert.equal(c(d, 'procedure').status, 'block'); });
test('a canceled surgery cannot pass', () => { const d = dataset(); d.procedures[0].status = 'revoked'; assert.equal(c(d, 'procedure').status, 'block'); });
test('a past scheduled procedure needs reconciliation', () => { const d = dataset(); d.procedures[0].occurrenceDateTime = new Date(now - 1000).toISOString(); assert.equal(c(d, 'procedure').status, 'review'); });
test('patient mismatch blocks the entire case', () => { const d = dataset(); d.observations[0].subject.reference = 'Patient/other'; assert.equal(run(d).status, 'blocked'); });
test('a matching suffix on another FHIR server is not a patient match', () => assert.equal(patientMatches({ subject: { reference: 'https://evil.test/Patient/demo-patient' } }, 'demo-patient', 'https://ehr.test/fhir'), false));
test('missing encounter prevents a reviewable checklist', () => { const d = dataset(); d.encounter = null; assert.equal(run(d).status, 'blocked'); });
test('a source retrieval failure blocks the case', () => { const d = dataset(); d.issues.push('Provenance unavailable'); assert.equal(run(d).status, 'blocked'); });
test('latest preliminary result cannot be overridden by an older final result', () => { const d = dataset(); d.observations.push({ ...structuredClone(d.observations[0]), id: 'new', status: 'preliminary', effectiveDateTime: new Date(now - 10000).toISOString() }); assert.equal(run(d).labs[0].status, 'review'); });
test('unsupported UCUM units do not get guessed from display text', () => { const d = dataset(); d.observations[0].valueQuantity.code = 'wrong'; assert.equal(run(d).labs[0].status, 'review'); });
test('equivalent platelet units normalize correctly', () => { const d = dataset(); d.observations[0].valueQuantity = { system: SYSTEM.ucum, code: '/uL', value: 242000 }; assert.equal(run(d).labs[0].value, 242); assert.equal(run(d).labs[0].status, 'pass'); });
test('quantity comparators do not turn into exact values', () => { const d = dataset(); d.observations[0].valueQuantity.comparator = '<'; assert.equal(run(d).labs[0].status, 'review'); });
test('future and date-only specimen times do not pass', () => { for (const t of ['2026-09-22T00:00:00Z', '2026-09-21']) { const d = dataset(); d.observations[0].effectiveDateTime = t; assert.equal(run(d).labs[0].status, 'review'); } });
test('LOINC panel components are evaluated', () => { const d = dataset(); const o = d.observations[0]; d.observations[0] = { ...o, code: { text: 'CBC panel' }, valueQuantity: undefined, component: [{ code: o.code, valueQuantity: o.valueQuantity }] }; assert.equal(run(d).labs[0].status, 'pass'); });
test('conflicting same-time results do not pass', () => { const d = dataset(); const o = structuredClone(d.observations[0]); o.id = 'conflict'; o.valueQuantity.value = 40; d.observations.push(o); assert.equal(run(d).labs[0].status, 'review'); });
test('lab-issued abnormal flags block even when numeric example range matches', () => { const d = dataset(); d.observations[0].interpretation = [{ coding: [{ code: 'A' }] }]; assert.equal(run(d).labs[0].status, 'block'); });
test('secondary abnormal interpretations are also respected', () => { const d = dataset(); d.observations[0].interpretation = [{ coding: [{ code: 'N' }] }, { coding: [{ code: 'HH' }] }]; assert.equal(run(d).labs[0].status, 'block'); });
test('fingerprint ignores retrieval time but detects evidence changes', () => { const d = dataset(), a = run(d), fp = caseFingerprint(d, a); d.fetchedAt = '2099-01-01'; assert.equal(caseFingerprint(d, a), fp); d.observations[0].valueQuantity.value = 48; assert.notEqual(caseFingerprint(d, a), fp); });
